defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ./checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "train/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "train/loss"
  patience: 5
  mode: "min"

model_summary:
  max_depth: -1
